# Generated by Django 5.2.8 on 2025-11-16 18:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('NIT', 'NIT')], max_length=3, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('receive_newsletter', models.BooleanField(default=False)),
                ('receive_promotions', models.BooleanField(default=True)),
                ('is_business', models.BooleanField(default=False, verbose_name='Cuenta Empresarial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('business_type', models.CharField(choices=[('SA', 'Sociedad Anónima'), ('SAS', 'Sociedad por Acciones Simplificada'), ('LTDA', 'Sociedad Limitada'), ('INDIVIDUAL', 'Persona Natural'), ('OTHER', 'Otro')], max_length=50, verbose_name='Tipo de Empresa')),
                ('tax_regime', models.CharField(blank=True, choices=[('RESPONSABLE_IVA', 'Responsable de IVA'), ('NO_RESPONSABLE_IVA', 'No Responsable de IVA'), ('GRAN_CONTRIBUYENTE', 'Gran Contribuyente'), ('REGIMEN_SIMPLE', 'Régimen Simple')], max_length=50, null=True, verbose_name='Régimen Tributario')),
                ('fiscal_address', models.CharField(max_length=255, verbose_name='Dirección Fiscal')),
                ('fiscal_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('fiscal_state', models.CharField(max_length=100, verbose_name='Departamento')),
                ('fiscal_postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('business_phone', models.CharField(max_length=17, verbose_name='Teléfono Empresarial')),
                ('business_email', models.EmailField(max_length=254, verbose_name='Email Empresarial')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('legal_representative', models.CharField(max_length=255, verbose_name='Representante Legal')),
                ('representative_document', models.CharField(max_length=20, verbose_name='Documento del Representante')),
                ('rut_document', models.FileField(blank=True, null=True, upload_to='business_documents/', verbose_name='RUT')),
                ('chamber_commerce', models.FileField(blank=True, null=True, upload_to='business_documents/', verbose_name='Cámara de Comercio')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Empresa Verificada')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Empresarial',
                'verbose_name_plural': 'Perfiles Empresariales',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('success', models.BooleanField(default=True, verbose_name='Inicio Exitoso')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Inicio de Sesión',
                'verbose_name_plural': 'Historial de Inicios de Sesión',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Nombre del destinatario')),
                ('recipient_phone', models.CharField(max_length=17, verbose_name='Teléfono del destinatario')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Dirección línea 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección línea 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento/Estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección predeterminada')),
                ('address_type', models.CharField(choices=[('home', 'Casa'), ('work', 'Trabajo'), ('other', 'Otro')], default='home', max_length=10, verbose_name='Tipo de dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de Envío',
                'verbose_name_plural': 'Direcciones de Envío',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
