# Generated by Django 5.2.8 on 2025-11-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('read', 'Leído'), ('in_progress', 'En Progreso'), ('replied', 'Respondido'), ('closed', 'Cerrado')], default='new', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas para uso interno del equipo', verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
