# Generated by Django 5.2 on 2025-11-29 02:07

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas internas del pedido')),
                ('shipping_address', models.JSONField(blank=True, help_text='Dirección de envío en formato JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó el pedido (puede ser null para invitados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Items del Pedido',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wompi_transaction_id', models.CharField(blank=True, help_text='ID de la transacción en Wompi', max_length=100, null=True, unique=True)),
                ('wompi_reference', models.CharField(help_text='Referencia única de la transacción', max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('CARD', 'Tarjeta de Crédito/Débito'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('BANCOLOMBIA', 'Bancolombia'), ('BANCOLOMBIA_TRANSFER', 'Bancolombia Transfer'), ('BANCOLOMBIA_COLLECT', 'Bancolombia Collect'), ('BANCOLOMBIA_QR', 'Bancolombia QR')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado'), ('ERROR', 'Error'), ('VOIDED', 'Anulado')], default='PENDING', max_length=20)),
                ('payment_method_data', models.JSONField(blank=True, default=dict, help_text='Datos específicos del método de pago (número de tarjeta enmascarado, banco PSE, etc.)')),
                ('redirect_url', models.URLField(blank=True, help_text='URL de redirección después del pago')),
                ('wompi_response', models.JSONField(blank=True, help_text='Respuesta completa de la API de Wompi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WompiWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('transaction.updated', 'Transacción actualizada'), ('nequi_token.updated', 'Token Nequi actualizado')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(help_text='Payload completo del webhook')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Evento Webhook',
                'verbose_name_plural': 'Eventos Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='payments_or_created_2e3458_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='payments_or_status_daab12_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='payments_or_custome_b0e8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='payments_pa_created_3147e3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['wompi_transaction_id'], name='payments_pa_wompi_t_52882e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['wompi_reference'], name='payments_pa_wompi_r_b612e3_idx'),
        ),
        migrations.AddIndex(
            model_name='wompiwebhookevent',
            index=models.Index(fields=['-created_at'], name='payments_wo_created_f3ea1e_idx'),
        ),
        migrations.AddIndex(
            model_name='wompiwebhookevent',
            index=models.Index(fields=['processed'], name='payments_wo_process_7a56b7_idx'),
        ),
        migrations.AddIndex(
            model_name='wompiwebhookevent',
            index=models.Index(fields=['transaction_id'], name='payments_wo_transac_735fd8_idx'),
        ),
    ]
